# Generated by Django 5.1.4 on 2026-05-15 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店名')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'レンタルショップ',
                'verbose_name_plural': 'レンタルショップ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='作者名')),
                ('author_kana', models.CharField(blank=True, max_length=200, verbose_name='作者ふりがな')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='出版社名')),
                ('magazine_label', models.CharField(blank=True, help_text='例: 週刊少年ジャンプ / ジャンプコミックス', max_length=200, verbose_name='掲載誌・レーベル')),
                ('status', models.CharField(choices=[('active', '進行中'), ('wishlist', 'いつか読みたい'), ('completed', '完結・読破済み')], default='active', max_length=20, verbose_name='ステータス')),
                ('current_volume', models.PositiveIntegerField(default=0, help_text='読破記録の最大巻から自動再計算される', verbose_name='読了済み巻数')),
                ('total_volumes', models.PositiveIntegerField(blank=True, help_text='完結作品のみ。連載中は空', null=True, verbose_name='全巻数')),
                ('favorite_score', models.PositiveSmallIntegerField(default=3, verbose_name='お気に入り度')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to=settings.AUTH_USER_MODEL, verbose_name='所有ユーザー')),
            ],
            options={
                'verbose_name': 'シリーズ',
                'verbose_name_plural': 'シリーズ',
                'ordering': ['-favorite_score', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RentalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.PositiveIntegerField(verbose_name='巻数')),
                ('rented_at', models.DateTimeField(verbose_name='レンタル日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='catalog.series', verbose_name='シリーズ')),
            ],
            options={
                'verbose_name': 'レンタル履歴',
                'verbose_name_plural': 'レンタル履歴',
                'ordering': ['-rented_at'],
                'unique_together': {('user', 'series', 'volume_number')},
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.PositiveIntegerField(verbose_name='巻数')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.series', verbose_name='シリーズ')),
            ],
            options={
                'verbose_name': 'カートアイテム',
                'verbose_name_plural': 'カートアイテム',
                'ordering': ['added_at'],
                'unique_together': {('user', 'series', 'volume_number')},
            },
        ),
        migrations.CreateModel(
            name='ShopAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', '貸出あり'), ('unavailable', '貸出なし')], max_length=15, verbose_name='貸出状況')),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='catalog.series', verbose_name='シリーズ')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='catalog.rentalshop', verbose_name='ショップ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '貸出状況',
                'verbose_name_plural': '貸出状況',
                'unique_together': {('series', 'shop')},
            },
        ),
        migrations.CreateModel(
            name='VolumeCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.PositiveIntegerField(verbose_name='巻数')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='画像URL')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='アップロード画像')),
                ('source', models.CharField(choices=[('rakuten', '楽天'), ('manual', '手動URL'), ('upload', 'アップロード')], max_length=10, verbose_name='取得元')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='catalog.series', verbose_name='シリーズ')),
            ],
            options={
                'verbose_name': '巻の表紙',
                'verbose_name_plural': '巻の表紙',
                'unique_together': {('series', 'volume_number')},
            },
        ),
    ]
