# Generated by Django 5.1.4 on 2026-05-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='status',
            field=models.CharField(choices=[('active', '進行中'), ('wishlist', 'いつか読みたい'), ('completed', '読破済み')], default='active', max_length=20, verbose_name='ステータス'),
        ),
    ]
