# Generated by Django 5.1.4 on 2026-05-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_series_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-favorite_score', 'publisher', 'title'], 'verbose_name': 'シリーズ', 'verbose_name_plural': 'シリーズ'},
        ),
    ]
